### ISSUE TITLE
Check for Receipt Blocks if Null

### ISSUE THREAD

**Issue by BryceAgent** [spruce-solutions/quai-manager#34]
```
Starting manager in location  [3 1]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7c5e75]

goroutine 1 [running]:
github.com/spruce-solutions/go-quai/core/types.(*ReceiptBlock).Header(...)
    /root/go/pkg/mod/github.com/spruce-solutions/go-quai@v0.0.0-20220219041746-11e1cbab8e69/core/types/block.go:654
main.(*Manager).fetchPendingBlocks(0xc0004b4400, 0x2)
    /root/quai-manager/manager/main.go:571 +0xd5
main.main()
    /root/quai-manager/manager/main.go:183 +0xf12
Error connecting to Zone mining node
Starting manager in location  [3 2]
Header for the Zone is nil, waiting for the Zone header to start mining
Header for the Zone is nil, waiting for the Zone header to start mining
Error connecting to Zone, context: 3 2
Starting manager in location  [3 3]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7c5e75]

goroutine 1 [running]:
github.com/spruce-solutions/go-quai/core/types.(*ReceiptBlock).Header(...)
    /root/go/pkg/mod/github.com/spruce-solutions/go-quai@v0.0.0-20220219041746-11e1cbab8e69/core/types/block.go:654
main.(*Manager).fetchPendingBlocks(0xc00042ce00, 0x2)
    /root/quai-manager/manager/main.go:571 +0xd5
main.main()
    /root/quai-manager/manager/main.go:183 +0xf12
Error connecting to Zone, context: 3 2
```

**Comment by BryceAgent** [comment]
https://github.com/spruce-solutions/quai-manager/commit/69f974efebb1411d9ecc399d2e47cd85270ff203
